### ISSUE TITLE
Startup crash after updating to 0.13.9, belt-sorter-lamp energy usage negative.

### ISSUE THREAD

**Issue by faerindel** [judos/beltSorter#1]
After updating to 0.13.9 from 0.13.8, Factorio runtimes with:

Error while loading entity prototype "belt-sorter-lamp": Energy usage per tick can't be negative.

**Comment by jorn86** [comment]
You only just beat me to it ;(

**Comment by judos** [comment]
Hi I'm afraid I will be abroad for two weeks, so I can't fix it right away. However as jorn86 mentioned correctly on #2 you can change the entitiy prototype to use an eneregy usage of 0kW instead. (See the prototypes/belt-sorter.lua).
Only backdraw is that the belt sorter will show a blinking no-energy sign.

**Comment by judos** [comment]
fixed with v 0.2.1
