### ISSUE TITLE
throughput too low 

### ISSUE THREAD

**Issue by zocke1r** [judos/beltSorter#12]
the standard version can not even keep up with a full compressed yellow belt, it appears it can only manage 1 side and a bit

**Comment by judos** [comment]
It depends also a bit on your filter, if you define one item twice then you will get twice the output, doing this for a different item onto a different output belt will make it possible to process a full yellow belt. If you need more output then I recommend having 2 beltSorter with the same filter to do the work.

Apart from that I agree that an advanced beltSorter should be implemented, I will try out a bit tonight.

**Comment by zocke1r** [comment]
well my current setup is having one full yellow belt go in and have 3 going out, with one main item and the sorter simply used to filter of side products, 
which i assumed would be one of the intended purposes but if a singular sorter cant keep up with a singular input belt then i was clearly wrong 

and concerning the idea of using two sorters my set up would require a grand total of 4 sorters, which given my current progression in game compared to the cost of the sorter less then desirable especially given the fact that for a lower price filter inserters could do the exact same job just using a bit more space

**Comment by judos** [comment]
Did you define the main item twice for the output direction? Defining it on 2 filter slots will usually increase output. Also it might help to place a fast-belt at the output tile such that the space is free quicker allowing the belt-sorter to place an item again.

I agree it should definitely be faster moving these items, especially since we have the stack filter inserter...

**Comment by zocke1r** [comment]
no i did not ,good to know but i have to say this should not be intended behaviour

**Comment by judos** [comment]
added an advanced belt-sorter which has also a left/right-lane only feature, see update 0.3.1
