### ISSUE TITLE
Naming of the directions

### ISSUE THREAD

**Issue by zocke1r** [judos/beltSorter#13]
Why did you go for cardinal directions(north, south, east,west) instead of relative directions(up,down,right,left) i think relative directions would be preferable, as the game does not have a cardinal directions and can only be derived form the convention that up means north.

Additionally why did you choose counterclockwise,  it feels counterintuitive to me

**Comment by judos** [comment]
True I could change the labels to Up/Down ...
I don't know why I went with this order, but changing it would mean everyone who is used to it will be confused. 
Maybe I can change the gui such that the slots are in the same direction in the ui as they stand for the real direction

**Comment by zocke1r** [comment]
i dont think it would really be confusing considering it would be rather obvious what directions are meant,

and i like the idea of changing the position of the input field, and maybe if possible center the gui in the middle of the screen instead of having it in the upper right corner

**Comment by judos** [comment]
Renamed the directions but left the gui as is, since there needs to be a lot of space for the item selection gui (and in the center it would lay behind the factorio gui for the belt-sorter-lamp/circuit condition)
See update 0.3.1
