### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Nexela** [judos/beltSorter#18]
Please add support for picker dollies.   See Bottleneck mod for examples, basically just requires registering the handler in on_init and on_load

Also if using get_transport_line()  store that in your global for faster script times

**Comment by judos** [comment]
What is a picker dolly? Can you explain in more details what you mean?

**Comment by Nexela** [comment]
Picker allows moving most entities.  Some mod added entities add additional entities so picker raises a move event to allow mods to listen and "correct" for the new location.

**Comment by judos** [comment]
I will have a look when I find time

**Comment by judos** [comment]
fixed with 0.5.2
