### ISSUE TITLE
Crash with 0.13.9

### ISSUE THREAD

**Issue by jorn86** [judos/beltSorter#2]
Since 0.13.9, it is apparently no longer allowed to have negative energy consumption. Loading the belt-sorter-lamp entity now crashes on startup. I tried changing it from -1KW to 0KW. The entity now loads correctly, but shows a blinking no energy sign (which, I assume, is why you set it to -1KW in the first place)

Awesome mod btw, looking forward to seeing the fix, I'm afraid I can't help you there.

**Comment by jorn86** [comment]
Duplicate of #1 :D

**Comment by judos** [comment]
Yes you are right with everything you mentioned :D thanks for the report!
