### ISSUE TITLE
Belt sorter inserts on to belts marked for deconstruction

### ISSUE THREAD

**Issue by BananaLumps** [judos/beltSorter#20]
As per title the belt sorter inserts on to belts marked for deconstruction causing construction robots to get stuck in a loop of removing items from the belt trying to get to the belt. 
This usually wouldn't be an issue but i use a mod that makes robots automatically replace belts with faster belts if available (Belt Upgrader mod)

**Comment by judos** [comment]
good point. Will have a look soon.

**Comment by judos** [comment]
fixed in 0.5.0
