### ISSUE TITLE
beltsortzer gui  suggests that it filters lanes too 

### ISSUE THREAD

**Issue by Smeagol001** [judos/beltSorter#21]

**Comment by Smeagol001** [comment]
the gui sugests that yxou can do make mixed belts bnut its not working that way it just adds both items on both beltlines  but the gui looks like it schod go item a on left item b on right

**Comment by judos** [comment]
hi there,
Can you post a screenshot?
I guess you are using the basic belt sorter?
Selecting left & right lanes are only supported by the tier2 "average belt sorter". priority for directing multiple output is then available with the tier3 "advanced belt sorter".
Does that help?

If you find it confusing, how would you change the ui?
thanks for the feedback.

**Comment by Smeagol001** [comment]
oh soo its not tree speeds of inserters soo its differemnt kinds of them

**Comment by judos** [comment]
it's both actually. One per belt speed and they also offer more functionality.
I think it should be described in the technology description. Maybe I can improve the text there...

**Comment by Smeagol001** [comment]
yeah since i thought i could filter with the first inserter i get since its
a longway to get some good filter things with angels bobs and omnimatter xD

2017-10-12 10:28 GMT+02:00 Julian <notifications@github.com>:

**Comment by judos** [comment]
Well yes with angels, bobs it takes quite a while to get the tech. But normally the tech requirements for the beltSorters are quite low to make them actually challenge the usage of filter inserters...
Still with the lowest beltSorter you can maybe use multiple sides to get the items on one belt but on different lanes :)
