### ISSUE TITLE
Update for .16?

### ISSUE THREAD

**Issue by ayeso** [judos/beltSorter#22]
I was wondering if there was plans for a .16 release?

**Comment by OfficialMaxBox** [comment]
Yes, please!

**Comment by judos** [comment]
Coming soon. I am abroad and can't update. But I just approved PR #23 by daanroeterink who is so nice and already fixed compatibility issues. He might upload a first version to the forum when it works.

**Comment by judos** [comment]
0.5.2 release on the modportal.
