### ISSUE TITLE
When trying to remove

### ISSUE THREAD

**Issue by alxrMironov** [judos/beltSorter#24]
Remove error fixed by updating. But still unkillable.

When trying to kill it with "C" - message "This cannot be damadged"

**Comment by alxrMironov** [comment]
And when trying to kill it with "C" - message "This cannot be damadged"

**Comment by judos** [comment]
which version are you using?

**Comment by alxrMironov** [comment]
At first im using yesterday's version from here. But after i am update to mod-portal version. First error gone, but second still.

**Comment by judos** [comment]
ok, please provide:
-savegame,
-modlist
-bigger description of your problem
otherwise I won't know what you mean.
