### ISSUE TITLE
Error when players try to join multiplayer

### ISSUE THREAD

**Issue by luckdemon** [judos/beltSorter#25]
Error happens when any player tries to connect to my server, both mod lists are identical, running the latest versions (beltsorter 0.5.4 as of this post)

https://cdn.discordapp.com/attachments/395057812280967178/395609983825346564/unknown.png

Error ClientMultiplayerManager.cpp:1075: mod-beltSorter was not registered for the following events when the map was saved but has registered them as a result of loading: Custom event (ID 181)
 454.837 Error ClientMultiplayerManager.cpp:95: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-beltSorter"
 454.837 Info ClientMultiplayerManager.cpp:573: MapTick(716) changing state from(ConnectedLoadingMap) to(Failed)

**Comment by judos** [comment]
sorry, was not playing factorio for quite a while, i'll close this since it seems outdated and for an old factorio version. I'll try to make an update for factorio 0.17.52 asap.
