### ISSUE TITLE
Bob's Logistics mod support

### ISSUE THREAD

**Issue by daxpedda** [judos/beltSorter#26]
Would it be possible to add support for the higher tier belts available in Bob's Logistics?
They work fine at the moment, just missing enough throughput to keep up.

Namely:
Faster transport belt
Extremly fast transport belt

Thanks!

**Comment by Cordina90** [comment]
Adding full compatibility with Bobs Logistics mod is on my to-do-list, but I haven’t had time lately.
Expect an update in a few weeks, when my holidays are finally there...

**Comment by judos** [comment]
Additionally mentioned in the mod portal discussions: Ultimate belts:
https://mods.factorio.com/mod/UltimateBelts

**Comment by judos** [comment]
Closed with release 0.6.2
