### ISSUE TITLE
Can No Longer Select Side or Modify Existing Sorter

### ISSUE THREAD

**Issue by w31don9** [judos/beltSorter#28]
Hey Judos, loving this mod but just recently ran into an issue. I'm running the latest 0.16.x version of Factorio and have used this mod without issue for more than a week now. 

Currently, when I place a new Belt Sorter, I can select the item/material to sort but I cannot select which side (Left/Right) for each filter, thus the belt will not sort as the respective side must be selected before it begins sorting. I checked the other Belt Sorters I had previously placed, which function as normal, but when I attempt to modify them, I run into the same problem of not being able to select/deselect the sides.

I hope I was able to explain the issue clearly enough, but if not, please let me know if I can offer any clarification or if you need any further information. Your time is most appreciated.

Thanks in advance!

**Comment by DreadWingKnight** [comment]
Copy and paste from an existing sorter does work.
0.16.19 is the version that broke it.

**Comment by DreadWingKnight** [comment]
Still present in 0.16.20 factorio btw

**Comment by w31don9** [comment]
Thanks for the info DWK. I just updated to 0.16.20 from 0.16.19 and can confirm the issue started with the previous version and continues presently. Praying there is a mod update to fix the issue soon.

Anything you can add to this, Judos?

**Comment by teckton** [comment]
Any word on a fix yet?

**Comment by DreadWingKnight** [comment]
Negative, 2 more minor releases (.21 and .22) and still present.

**Comment by Cordina90** [comment]
fixed in version 0.5.5

**Comment by judos** [comment]
Retested on factorio 0.17.52, looking good. If there is still problems please reopen :) Thanks Cordina for the fix!
