### ISSUE TITLE
No balancing

### ISSUE THREAD

**Issue by Nekothika** [judos/beltSorter#29]
Hi, why nothing on down ? https://i.imgur.com/OY6eiLX.jpg

**Comment by DreadWingKnight** [comment]
You have left set as priority 1. Until it fills, down which is priority 2 won't start filling

**Comment by judos** [comment]
Hi @Nekothika ,
Long time ago I know.. If it was not solved: You should have clicked the button 1 for the down row, such that the bottom output receives first priority.
