### ISSUE TITLE
issue with 0.16.23

### ISSUE THREAD

**Issue by Luf2K14** [judos/beltSorter#30]
Hi!
i love this mob btw :) but in v0.16.23 it doesnt work it doesnt let me choose left/right side of the belt when i press the square to work it refuses and this was really awesome mod can you update it please to support the v0.16.23 please?

**Comment by asw122** [comment]
Also having this problem. The basic sorter works, but the two improved version with left/right tickboxes don't.

**Comment by tomkcook** [comment]
The problem here seems to be that the `click` event on the checkboxes is being received twice when the user clicks - I'll fork & create a pull request to fix in a minute.

**Comment by tomkcook** [comment]
See https://github.com/tomkcook/beltSorter, which includes a 0.5.5 release which works with 0.16.36 (on Linux, at any rate).

**Comment by Cordina90** [comment]
fixed in version 0.5.5

**Comment by Luf2K14** [comment]
i saw in the factorio mod portal thanks:)
________________________________
De: Cordina90 <notifications@github.com>
Enviado: 22 de julho de 2018 09:43
Para: judos/beltSorter
Cc: Luf2K14; Author
Assunto: Re: [judos/beltSorter] issue with 0.16.23 (#30)


fixed in version 0.5.5
