### ISSUE TITLE
Error when opening power armor grid

### ISSUE THREAD

**Issue by wc5879** [judos/beltSorter#31]
Hi 
When this mod is turned on, when I open the grid of power armor I get the following error message:

Error while running event beltSorter::on_tick (ID 0)
LuaEquipmentGrid doesn't contain key name.
stack traceback:
	__beltSorter__/libs/control/gui.lua:96: in function 'playerOpenGui'
	__beltSorter__/libs/control/gui.lua:126: in function 'gui_tick'
	__beltSorter__/control.lua:49: in function <__beltSorter__/control.lua:47>

**Comment by Cordina90** [comment]
As judos doesn't seem to be around, you can (temporary) fix this yourself.
Check out my pull request te see what changes you'll have to make

**Comment by Cordina90** [comment]
fixed in version 0.5.5

**Comment by judos** [comment]
Thanks @Cordina90 for the fix!
