### ISSUE TITLE
Please make it works with Bobs basics betls.

### ISSUE THREAD

**Issue by alxrMironov** [judos/beltSorter#34]

**Comment by Cordina90** [comment]
Adding full compatibility with Bobs Logistics mod is on my to-do-list, but I haven’t had time lately.
Expect an update in a few weeks, when my holidays are finally there...

**Comment by alxrMironov** [comment]
Still not working with bob mod. (With bobs belt overhaul)

**Comment by alxrMironov** [comment]
Closed. Issue caused by another mods.

**Comment by judos** [comment]
See also #26
