### ISSUE TITLE
crash then opening power armor

### ISSUE THREAD

**Issue by mcproprot** [judos/beltSorter#35]
https://pastebin.com/rV9Nieex

**Comment by Cordina90** [comment]
As judos doesn't seem to be around, you can (temporary) fix this yourself.
Check out my pull request te see what changes you'll have to make.
I’ll be releasing a new version soon.

**Comment by Cordina90** [comment]
Please download the new versioon (0.5.5) from the portal, this fixes your issue

**Comment by judos** [comment]
Thanks for the stacktrace! I put a todo tag in the source to check it again for the newest version.

**Comment by judos** [comment]
Yeah looking good on 0.17.52 as well, actually the modular armor closes the open belt-sorter gui (the vanilla gui, not the modded top left one), but if you close the modular armor it reopens it, so I think it works fine like this
