### ISSUE TITLE
Downloading belt sorter doesn't work

### ISSUE THREAD

**Issue by Cana00** [judos/beltSorter#36]
Hi. When i open factorio with this mod is downloaded, the downloading stops at 40 per cent and a message appears to me: no picture to put in atlas.

**Comment by Cordina90** [comment]
I haven't heared of this one before.
Please remove the mod and download the most recent version.
If this doesn't fix the issue, please post an screenshot of the exact error message

**Comment by judos** [comment]
Closing as old issue, seems to work fine for newest version. Maybe it was a temporary issue with mod portal...
