### ISSUE TITLE
Do these interact with themselves in a good maner? - They don't work with loaders.

### ISSUE THREAD

**Issue by xGnoSiSx** [judos/beltSorter#38]
Hi,

1. I note that loaders don't work with these at all. Any plans to fix this?

2. Do sorters work, passing items from one to another, if you have 2 of them adjacent?

**Comment by Cordina90** [comment]
To answer your points, when using loaders or multiple sorters, please ensure there is at least one (1) regular belt between the loader and the sorter or between the sorters.
This way it’ll work.

**Comment by xGnoSiSx** [comment]
> 
> 
> To answer your points, when using loaders or multiple sorters, please ensure there is at least one (1) regular belt between the loader and the sorter or between the sorters.
> This way it’ll work.

Hi Cordina,

Yes, I know that, but was questioning why they don't work one next to another.

**Comment by judos** [comment]
We had a PR to make them work with loaders: #41 
Directly adjacent belt-sorters don't work yet. Appended for the todo list.

**Comment by judos** [comment]
Tracking new features in #43
