### ISSUE TITLE
Request: Remove energy reqirements option

### ISSUE THREAD

**Issue by WardenCommander** [judos/beltSorter#39]
Hello Judos,
first of all great mode. 
I how could I change energy requirements of Sorters? Or to remove it?

Also could you make it compatible with loaders?
https://mods.factorio.com/mod/DeadlockLoaders

**Comment by judos** [comment]
Hi, sorry was not up-to-date for a long time. We had a PR to make them work with loaders #41. Might work for DeadlockLoaders as well (soon). But the power configuration is a good idea.

**Comment by judos** [comment]
There is now a setting to remove energy requirement in 0.6.4. Hf!
