### ISSUE TITLE
[Fac 0.13.10] LuaSurface::find_entities in a single tile kills FPS/UPS

### ISSUE THREAD

**Issue by faerindel** [judos/beltSorter#4]
Had to take out the only belt sorter I had in the map to make the game playable.

It's like Factorio devs are updating stuff just to break this mod. :P

**Comment by judos** [comment]
Hi Faerindel,
Thanks for the report, i'm on vacation for another week, I will fix it when I'm back.
In the meantime, were there other reports of this problem in the factorio bug section? Maybe other mods have already reported similar issues?

**Comment by faerindel** [comment]
0.13.11 changed find_entities again. And now it is a lua error and kicks you to the main menu:

Error while running the event handler: __beltSorter__/control/belt-sorter.lua:282: An area of zero size is not supported. Either don't define area to search the entire surface or use 'position'.

**Comment by judos** [comment]
closed with v 0.2.1
