### ISSUE TITLE
Russian translation update

### ISSUE THREAD

**Issue by traiben** [judos/beltSorter#46]
the current translation is no longer relevant and not complete

[entities.txt](https://github.com/judos/beltSorter/files/3587381/entities.txt)
[gui.txt](https://github.com/judos/beltSorter/files/3587382/gui.txt)
[item-group-names.txt](https://github.com/judos/beltSorter/files/3587383/item-group-names.txt)
[items.txt](https://github.com/judos/beltSorter/files/3587384/items.txt)
[logging.txt](https://github.com/judos/beltSorter/files/3587385/logging.txt)
[settings.txt](https://github.com/judos/beltSorter/files/3587386/settings.txt)
[technologies.txt](https://github.com/judos/beltSorter/files/3587387/technologies.txt)

**Comment by Cordina90** [comment]
Thanks, will be included in the next release
