### ISSUE TITLE
[bug]  Must have a valid fuel_category when fuel_value is used

### ISSUE THREAD

**Issue by truepatch** [judos/beltSorter#47]
Not compatible with mods [NicerFuelGlow](https://mods.factorio.com/mod/NicerFuelGlow) or [Bioluminescence](https://mods.factorio.com/mod/Bioluminescence)

```

232.188 Error ModManager.cpp:1514: Error while running setup for item prototype "belt-sorter1" (item):
Must have a valid fuel_category when fuel_value is used.

212.245 Error ModManager.cpp:1514: Error while loading item prototype "belt-sorter1" (item):
Must have a fuel_value when
fuel_acceleration_multiplier,
fuel_top_speed_multiplier,
fuel_emissions_multiplier,
or fuel_glow_color are used.

```
see the fix implementation as an example, I think you will quickly fix the problem [z-SP-fuel-fix](https://mods.factorio.com/mod/z-SP-fuel-fix)

**Comment by snouz** [comment]
NicerFuelGlow isn't up to date, so I can't check, but Bioluminescence works without problem. This ticket is probably way out of date.
