### ISSUE TITLE
Bugs in Factorio v1.1 Version 

### ISSUE THREAD

**Issue by dbiser99** [judos/beltSorter#48]
I posted this in the discussion thread I was in but also saw the note that was added about posting to the forum or github. Little out of context as I just did a straight cut and paste but the relevant info should be there. As mentioned below I'm going to keep looking, but at the moment I'm not sure I can get it any further.

> I haven't downloaded the official update yet, but I haven't noticed any issues yet with the changes I posted earlier in this thread...what should I be looking for? Not much of a lua programmer myself (I'd go as far as saying I'm not) but I've had some success in fixing problems I've run into when the mod devs are slower to react and I want something to work. If it's something I can figure out for you, happy to help. I could even just send you my version of it if it helps. It almost wasn't worth it as I still use the blue ones almost exclusively, but for what I wanted the mod for I added (or re-added...I think I saw remarked out code that you may have had it in there at one point) the lane sorting and priorities to all levels and rebalanced the research time to be the same across all three levels. (Brought level 1 down to match 2 & 3.)
> 
> Edit: I noticed the list of known issues on the home page...I'm not having any issues with robot placement directly, or blueprinting for that matter. What I'm getting for an error seems to be related to the storage and recall of filter settings. A new placement by ghost/robot or a blueprint with no filters saved works fine. A blueprint with filters or copying & pasting an existing sorter (with filters) causes an error though. I'm looking into it to see what I might be able to figure out, but as mentioned, I'm not really a programmer myself (just seem to be good with tracing errors) and wouldn't hold my breath. So far I've been able to get it to stop throwing an error so you can blueprint or copy a sorter with an active configuration, but it doesn't actually paste the configuration settings into the new entity. To do that I ended up remarking out almost the entire beltSorterGui.storeConfigToCombinator function (lines 207-229 specifically) in belt-sorter-gui.lua. I'm still looking, but as far as I could tell it didn't actually do anything anyway...created some local variables, did some things to one of them and sent the results back to the other. Everything except the ability to blueprint and/or paste an entity with settings seems to be working without it. (Pasting from the Copy/Paste in the sorter's gui works.)

**Comment by Cordina90** [comment]
I saw your post in the mod portal discussion. I'm working on v1.1 errors of multiple mods now, so if you have valuable information or possible fixes, please post here and/or make a pull request
