### ISSUE TITLE
Belt Sorter Crashes Game

### ISSUE THREAD

**Issue by imRoage** [judos/beltSorter#49]
Howdy,

Below is the error code I received when placing a 3rd Level Belt Sorter and attempting to assign an item to a slot within the Sorter Gui:

The mod ControlTech (1.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event ControlTech::on_gui_checked_state_changed (ID 3)
__ControlTech__/control.lua:160: attempt to index local 'gui_frame' (a nil value)
stack traceback:
	__ControlTech__/control.lua:160: in function <__ControlTech__/control.lua:151>

------------

I tried direct placing the sorter.
I tried placing it through a ghost/bot.
I click a slot.
The choose item dialog opens.
I select the item.
I click to close the dialog.
The crash screen dialog opens with this message.
It only crashes back to the main menu.
I does not crash the entire Factorio process.
The same result occurs with the level 2 Sorter.
This began occurring after the most recent Factorio Bug Fix that came down 2/8/2021

I hope this helps,

By the way. I really love this sorter as it has an extremely low footprint and allows for a real tidy belt configurations.

Warm Regards,
Roage

**Comment by snouz** [comment]
Thanks for the report, but I guess this problem has been patched in the meantime, because I can't reproduce this problem at all. ControlTech and BeltSorter are working together without crashing.
