### ISSUE TITLE
Crash with 5Dims mod - New Energy

### ISSUE THREAD

**Issue by Tamperold** [judos/beltSorter#52]
Hi,

your mod crash while the game is loding.
Error:
**Error while running setup for entity prototype "belt-sorter-lamp4" (lamp): next_upgrade target (5d-lamp-02) must have the same bounding box.**
Is there a easy manuel fix or workaround?

Thx

Edit:
belt sorter: 0.8.0
5Dims mod: 1.1.3

**Comment by snouz** [comment]
Thanks for the report, I found the fix!
