### ISSUE TITLE
Offering help as a maintainer/graphic designer

### ISSUE THREAD

**Issue by snouz** [judos/beltSorter#53]
Hi Judos !

I've been working on various mods lately, improving graphics mainly, but also mod pages, code bits, fixing bugs, sorting mod page threads...

And since I noticed you don't seem to be active anymore, I wanted to offer my help as a maintainer/contributor.
Here's some of my contribution in factorio:
https://mods.factorio.com/mod/MbrTestMod
https://github.com/snouz

If you're up for it, invite me as a contributor on the mod portal and on github !
You can also contact me on discord snouz#0489

**Comment by judos** [comment]
Hi snouz,
Thanks for offer. I will add you as contributor so you can do what's best for the mod :)

I couldn't find you on discord though, is there a digit missing on the number you posted?
If you need any help feel free to ask me on discord: judos#7996

Cheers, judos

**Comment by snouz** [comment]
Thansk :) I'll make a fork and see what can be improved
I made a typo, it's snouz#0489.
Cheers

**Comment by judos** [comment]
Oh github doesn't show 0 after the hashtag because that's probably a link to a ticket.
Closing this ticket since you have access to modportal and github.
