### ISSUE TITLE
Hidden items show up in the item list

### ISSUE THREAD

**Issue by Nexela** [judos/beltSorter#8]
Hidden items show up in the item selection list. (one example is the proxy lamp and combinator from smart trains)  As these items can't be produced anyway a simple hidden check can remove them from the list

https://github.com/judos/beltSorter/blob/master/source/libs/itemSelection/control.lua#L74

`if not prototype.has_flag("hidden") and (filter == "" or string.find(name,filter)) then`

**Comment by judos** [comment]
Ah nice, didn't see that yet :) thanks for the hint! Will change it with next version.
